baseURL: https://mhyrzt.github.io
languageCode: en-us
title: Mahyar Blog
theme: "PaperMod"

enableRobotsTXT: true

params:
  env: production
  author: Mahyar Riazati
  keyowrds: [Blog, Portfolio, Mahyar, mhyrzt, Riazati]
  defaultTheme: light

  ShowToc: true
  ShowBreadCrumbs: true
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true

  comments: false
  
  editPost:
    URL: "https://github.com/mhyrzt/mhyrzt.github.io/content"
    Text: "Suggest Changes"
    appendFilePath: true

  homeInfoParams:
    Title: "👋 Hello There!"
    Content: '> "*Writing is utter solitude, the descent into the cold abyss of oneself.*" -Franz Kafka'

  socialIcons:
    - name: github
      url: "https://github.com/mhyrzt"
    - name: linkedin
      url: "https://www.linkedin.com/in/mhyrzt/"
    # - name: youtube
    #   url: ""
    # - name: cv
    #   url: ""
    - name: buymeacoffee
      url: "https://www.coffeebede.com/mhyrzt"
  
  assets:
    disableHLJS: true
    favicon: "/favicon/favicon.ico"
    favicon16x16: "/favicon/favicon-16x16.png"
    favicon32x32: "/favicon/favicon-32x32.png"
    apple_touch_icon: "/favicon/apple-touch-icon.png"

menu:
  main:
    - identifier: tags
      name: Tags
      url: /tags/
    - identifier: archive
      name: Archive
      url: /archives/
    - identifier: search
      name: Search
      url: /search/
    - identifier: about
      name: About Me
      url: /about/


outputs:
  home:
    - HTML
    - RSS
    - JSON
